# Generated by Django 4.2.11 on 2024-04-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photos/'),
        ),
    ]
